### ISSUE TITLE
"in-history" includes current year

### ISSUE THREAD

**Issue by Kevin2kkelly** [InsertDisc/pattrmm-develop#1]
I have pattrmm set to run daily at 5am, ran this morning without issue and added three movies whose release date is an increment of 5 years prior to today. I added a movie released today to Plex after that run, and re-ran pattrmm to test out some of the TV functionality, and the movie released today was added to my "This day in history" trakt list.

I'm not sure if this is intentional, but I could potentially be alleviate it on the PMM side by filtering current year releases if it is.
[pattrmm 10.6.23.txt](https://github.com/InsertDisc/pattrmm-develop/files/12835378/pattrmm.10.6.23.txt)

**Comment by InsertDisc** [comment]
It is neither 'intended' or 'unintended' behavior.  It's a super easy change to make. I've not had any other feedback on which way anyone expects that behavior.

**Comment by InsertDisc** [comment]
Updated to only included items not released in the current year.
